### ISSUE TITLE
sbocheck should list package names without versions to make selecting for upgrade easier

### ISSUE THREAD

**Issue by hackedhead** [pink-mist/sbotools#10]
Current Format of sbocheck output:
dmenu-4.5          <  needs updating (SBo has 4.6)
jdk-7u71           <  needs updating (SBo has 8u66)

However:

[21:58] root@koopa:/data# sboupgrade jdk-7u71
Unable to locate jdk-7u71 in the SlackBuilds.org tree.

It would be nice to separate the version from the package name to make "click to select word" in X terminals select only the package name for pasting into an sboupgrade command.

dmenu (current 4.5, SBo has 4.6) or similar

**Comment by pink-mist** [comment]
This does sound like an improvement. Will get to it when I can =)
