### ISSUE TITLE
sbocheck and sboupgrade should consider local overrides

### ISSUE THREAD

**Issue by hackedhead** [pink-mist/sbotools#11]
They do not appear to as of sbotools-1.10RC1

**Comment by pink-mist** [comment]
I can't get ```sbocheck``` to reproduce this bug; it uses my local overrides without issue. Have yet to try sboupgrade.

**Comment by pink-mist** [comment]
Seems this was caused by trying to upgrade packages included in slackware to begin with. That's not something sbotools will support.

**Comment by pink-mist** [comment]
Note that you can still removepkg the one included in slackware and then sboinstall from your local overrides if you fancy. So long as your local overrides slackbuild script provides a ```_SBo``` tag, sbotools will then be happy to look after it.
