### ISSUE TITLE
Parsing SlackBuild $PKG.info REQUIRES

### ISSUE THREAD

**Issue by bgrundy** [pink-mist/sbotools#2]
Currently, sboinstall reads the REQUIRES line of $PKG.info and attempts to install second depth dependencies FIRST.  In some cases, this results in either failed builds, or builds that may complete, but fail with errors during use.  It would make more sense to have the REQUIRES line read in linear fashion, inserting and building dependencies as needed.  This would give the SBo maintainer more control over the order of installation.  

Real example:  dfvfs (on SBo).  From the REQUIRES line:

REQUIRES="construct protobuf libbde libewf libqcow libsmdev libsmraw libvhdi libvmdk libvshadow pytsk"

"sboinstall dfvfs" results in:

Install queue: sleuthkit pytsk libvshadow libvmdk libvhdi libsmraw libsmdev libqcow libewf libbde pysetuptools python-gflags six python-dateutil pytz protobuf construct dfvfs

This will break the installation because while libewf is optional for sleuthkit, the package we are installing (dfvfs) requires that sleuthkit be built with libewf support (and dfvfs is a dependency of plaso which requires the same).

if the package were build using the linear order of the REQUIRES line, it would look like this (secondary deps are in parentheses for illustration):

Install queue: (six) construct (pysetuptools python-gflags python-dateutil pytz) protobuf libbde libewf libqcow libsmdev libsmraw libvhdi libvmdk libvshadow (sleuthkit) pytsk

With REQUIRES read linearly, the maintainer can specify that libewf should be installed prior to sleuthkit (for pytsk), and so sleuthkit is built with proper options for this package.

**Comment by pink-mist** [comment]
@bgrundy Sorry it took so long. Would welcome some feedback if this works for you.

**Comment by bgrundy** [comment]
...and I'm sorry it took so long to get you feedback...I've finally build the newest version of Plaso (which was the impetus for this issue).  The build queue in the info file works as expected with sbotools 2.3.   I appreciate the work you did on this.
