### ISSUE TITLE
Using already built  packages by sboinstall and sboupgrade

### ISSUE THREAD

**Issue by travis-82** [pink-mist/sbotools#29]
It would be better if already built packages in PKG_DIR (those who match VERSION field in the info file) used by sboinstall and sboupgrade instead of current duplicated building approach.  That would be more hardware friendly and saves the time needed for package building specially for users who reinstall their system very often.

**Comment by pink-mist** [comment]
I can see a valid argument for adding this functionality, but you could just ```installpkg``` those packages instead. I fear that anything we try to make sbotools do with regards to this will at best be errorprone, or at worst not working at all.
