### ISSUE TITLE
Support templates for rapidly configuring multiple systems

### ISSUE THREAD

**Issue by hackedhead** [pink-mist/sbotools#38]
slackpkg has a few commands for handling groups of packages, generate-template, install-template, remove-template. These allow the capture and recreation of sets of packages, like slackware's tagfiles to allow for rapidly configuring multiple machines with the same package sets.

**Comment by pink-mist** [comment]
Alright, this feature request needs a bit of brainstorming to figure out how to implement it nicely ...

What would be the interface to it?
* A completely new ```sbotemplate``` command? How should that be used if so?
* A couple of switches to ```sboinstall```? Say ```sboinstall --create-template template.name``` and ```sboinstall --use-template template.name```? Should using a template imply ```--nointeractive```?
* Should ```sboupgrade``` have any support for it? How?

What features should it actually have? ```slackpkg``` being for slackware proper it doesn't need to worry about dependencies and such, nor about build options or the need to run commands to add users/groups.
* Should SBos that have user/group commands be specified in the template?
* Should SBos that have environment variables be specified in the template?

**Comment by pink-mist** [comment]
Also, how should it deal with compat32 needs? Some things might simply not build on 64bit or 32bit, some things might need multilib to build on 64bit.

**Comment by pink-mist** [comment]
Should it be feasible/possible/easy to write a template file manually?

**Comment by pink-mist** [comment]
I'm probably leaning more towards having ```--create-template``` and ```--use-template``` switches for `` sboinstall``` currently, and not having any support for it in ```sboupgrade```, since an ```sboupgrade --all``` should be more than enough.
