### ISSUE TITLE
Problem with parallel builds

### ISSUE THREAD

**Issue by tom-crane** [pink-mist/sbotools#41]
Dear Maintainer,
   I noticed the command line option '-j' and the sbotools.conf 'JOBS' variable seem to have no effect on sboinstall runs. Looking at the modified SlackBuild script, eg. 
/var/lib/sbo/repo/graphics/inkscape/inkscape.SlackBuild, the make process is done by a plain, unchanged 'make' line and parallel compilation does not occur, which is pity on a multi-core machine. I am attaching a patch to fix this problem.  My details;

OS: Slackware-current (32-bit)
sbotools version: 2.0RC7

Would you be prepared to incorporate the patch?

Thanks
Tom Crane
[SBO-Lib.pm.makeopts.zip](https://github.com/pink-mist/sbotools/files/215605/SBO-Lib.pm.makeopts.zip)

**Comment by pink-mist** [comment]
Thanks, I'll apply the patch and run some tests for it, and if all looks good I'll include it =)
