### ISSUE TITLE
tp_smapi and vhba-module

### ISSUE THREAD

**Issue by Sammyboy** [pink-mist/sbotools#43]
Hi,
on my Thinkpad with Slackware-current, I made an "sboupgrade -all" which finished ok, but when i do "sbocheck" again, it shows two packages which have already been upgraded:

- tp_smapi
- vhba-module

When I do "sboupgrade -all" again, it rebuilds the packages and on the next "sbocheck" those packages reappear in the list.

**Comment by pink-mist** [comment]
The reason is because the slackbuild scripts append the kernel version to the version string, so instead of ```tp_smapi-0.41-...``` it becomes ```tp_smapi-0.41_4.4.13-...```, or whatever kernel version you're using. It's the same for the vhba-module version string.
