### ISSUE TITLE
sbocheck says openoffice needs updating

### ISSUE THREAD

**Issue by STDOUBT** [pink-mist/sbotools#45]
sbocheck wants to update openoffice even though it's already installed.

---

[root@~]# sbocheck 
Updating SlackBuilds tree...
          4,586   0%    1.84kB/s    0:00:02 (xfr#1, to-chk=0/36007)  
Checking for updated SlackBuilds...
openoffice.org 4.1.2_en_US  <  needs updating (4.1.2 from SBo)
A copy of the above result is kept in /var/log/sbocheck.log
[root@~]# ls /var/log/packages/ |grep openoffice
openoffice.org-4.1.2_en_US-i586-1_SBo

---

Here is the end of the "sboupgrade --all" run:

---

Executing install script for openoffice.org-4.1.2_en_US-i586-1_SBo.tgz.
Package openoffice.org-4.1.2_en_US-i586-1_SBo.tgz installed.
Package openoffice.org-4.1.2_en_US-i586-1_SBo upgraded with new package /tmp/openoffice.org-4.1.2_en_US-i586-1_SBo.tgz.
Cleaning for openoffice.org-4.1.2...

---

Thank you for this awesome software, I wish I knew how to fix this little glitch!!!

**Comment by pink-mist** [comment]
Oh, this is similar to #43.

I'll need to consider how to solve this neatly.
