### ISSUE TITLE
Error when parsing PAC.info file

### ISSUE THREAD

**Issue by crish4cks** [pink-mist/sbotools#46]
Hi,
about a week ago I submitted a SlackBuild script for PAC (Perl Auto Connector). Today I tried to install it but I receive the following error:

bash-4.3# sboinstall PAC
A fatal script error has occurred:
error when parsing PAC.info file. Line: perl-Gtk2-Unique perl-IO-Stty 
perl-Net-ARP perl-Socket6 perl-yaml uuid
Exiting.
bash-4.3#

Thank you in advance for your time.

**Comment by pink-mist** [comment]
If an entry in the .info file spans more than one line, the second line needs to start with atleast one space character.

Unsure if this is documented anywhere.

Ideally, sbotools should be able to parse it anyway though, so I'll consider this a real bug and see what I can do to fix.

**Comment by crish4cks** [comment]
Ok, thank you very much pink-mist.
Anyway, in the meantime I've resubmitted the script after having added a space into the PAC.info file.
