### ISSUE TITLE
sbofind: Exact matches?

### ISSUE THREAD

**Issue by drgibbon** [pink-mist/sbotools#48]
I am trying to search for the package [R](https://slackbuilds.org/repository/14.2/academic/R/) with `sbofind`, and it takes a very long time (I guess it is going to return all packages containing the character 'r'). Is there any way to restrict `sbofind` results to exact matches?

**Comment by pink-mist** [comment]
Seems like this could be improved, yes ... first thing to do would be to make it faster, then to provide a way to limit results to exact matches.

**Comment by pink-mist** [comment]
Seems like this can be closed thanks to @chinarulezzz patch which adds an --exact and a --no-tags option.

**Comment by drgibbon** [comment]
Very cool, thanks @chinarulezzz
