### ISSUE TITLE
sboinstall does not work but sbopkg works with arpack and smplayer

### ISSUE THREAD

**Issue by iluvatar1** [pink-mist/sbotools#55]
Dear all, 

First of, thanks for this awesome tools.

This is very strange and I would like to know if I am doing something wrong or if there is a fundamental difference but, for packages like arpack and smplayer I got errors for downloading with sboinstall but sbopkg works without any problem. 

In both cases, sboinstall fails with the error
No such directory 'sbosrcarch/by-md5/\\//\\'
although I can browse ftp://slackware.uk/sbosrcarch/by-md5 

I compared both slackbuilds from sbotools and sbopkg and they are the same. So I wonder if there is a subtle diff between the config of this tools (which might be interesting for everybody) or I am doing something wrong (which of course is my own problem).

INFO:
sbotools 2.2
Slackware64 14.2

Thanks in advance.

**Comment by pink-mist** [comment]
Thanks for this bugreport, and I can see what the issue is - if you use sbotools-2.0 it shouldn't have this problem ... will try to fix this asap.
