### ISSUE TITLE
Issue with texlive

### ISSUE THREAD

**Issue by crish4cks** [pink-mist/sbotools#56]
Hi,
I encountered an issue when trying to install texlive with _sboinstall texlive_
Here below I report some details which maybe could help. Thanks in advance for your time.
[texlive.txt](https://github.com/pink-mist/sbotools/files/721102/texlive.txt)

**Comment by pink-mist** [comment]
This was fixed in version 2.3.

**Comment by crish4cks** [comment]
Thank you!
