### ISSUE TITLE
sboinstall does not allow reinstalls

### ISSUE THREAD

**Issue by montagdude** [pink-mist/sbotools#58]
If you use sboinstall to attempt to reinstall a package, it will notify you that the package is already installed and then quit. Sometimes reinstalling is warranted, though, for example if a dependency was upgraded in a non backwards-compatible way. Since sboinstall already uses `upgradepkg --reinstall --install-new`, there should be no reason not to allow reinstalls. The warning could give the option to continue or quit, instead of just quitting.

**Comment by pink-mist** [comment]
I agree

**Comment by montagdude** [comment]
Great, I'm looking forward to the enhancement. Thanks.
