### ISSUE TITLE
SBo new git server

### ISSUE THREAD

**Issue by drgibbon** [pink-mist/sbotools#62]
There recently been a change in the git/cgit addresses for SBo due to the new server ([see here](https://www.linuxquestions.org/questions/slackware-14/slackbuilds-org-git-and-cgit-services-migrated-to-new-server-4175606019/));
> git://slackbuilds.org/slackbuilds.git is now git://git.slackbuilds.org/slackbuilds.git

**Comment by pink-mist** [comment]
Yes, this is true, but by default sbotools uses rsync to get the data from SBo. Any git usage is something the user set up in the config on their own. They can fix it themselves too.

**Comment by drgibbon** [comment]
Ok thanks, wasn't sure if it was relevant or not. Obviously not!
