### ISSUE TITLE
Feature request: automatic dependency installation with an argument

### ISSUE THREAD

**Issue by nikonikolov** [pink-mist/sbotools#63]
It would be great if there is a flag that allows for automatically agreeing to install all dependencies for a package and then proceeding. I agree that usually it is good to see what dependencies you are installing and I personally do this every time. However, this flag is very good for automation, in the case that you are invoking sbotools from a script. For example, I am enabling ROS for Slackware and it needs to invoke `sboinstall` from a script in order to install dependencies. 

Again, this will be just a flag and not the default behavior, so default installation process will not be touched.

**Comment by pink-mist** [comment]
Sorry, this is not something that will be implemented. Something else that should be useful for your usecase though, is the --create-template and --use-template options to sboinstall.
