### ISSUE TITLE
sbofind 2.5 exact option broken?

### ISSUE THREAD

**Issue by drgibbon** [pink-mist/sbotools#71]
Not sure if it's intended, but it doesn't seem possible to match exact searches with sbofind 2.5. For example, `sbofind -et ffmpeg` now returns quite a few hits (exactly the same list as `sbofind -t ffmpeg`).

**Comment by drgibbon** [comment]
Any news?

**Comment by drgibbon** [comment]
Unfortunately I don't think 2.6 fixed this:

```console
root@slack:~# sbofind ffmpeg | wc -l
24
root@slack:~# sbofind -e ffmpeg | wc -l
24
root@slack:~# sbofind -et ffmpeg | wc -l
24
```
or a worse search example:
```console
root@slack:~# sbofind -e R | wc -l
9837
```

**Comment by pink-mist** [comment]
Darn, I had the fix in another repository which I thought I had brought in for 2.6, but it seems I had missed 2 characters when copying it over ... will release a fix tomorrow.
